library "javaRIG"

pipeline {
  agent {
    docker {
      image "cimg/openjdk:17.0.5"
    }
  }
  stages {
    stage("Compile Project"){
      steps{
        script {
          maven.execute("compile")
        }
      }
    }
    stage("Build Project") {
      steps{
        script {
          maven.execute("clean install",[skipTests : null])
        }
      }
    }
    stage("Test Project") {
      steps{
        script {
          maven.execute("clean test")
        }
      }
    }
  }
}